project:
  type: book
  pre-render: quarto render template/prelims
  post-render: ./template/prelims/cleanup.bash

book:
  title: "Prolly Trees for State-Based CRDTs"
  author: "Doran Penner"
  date: "May 2026"
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - chapters/background.qmd
    - chapters/construction.qmd
    - chapters/operations.qmd
    - chapters/improvements.qmd
  # add if you want a dedicated appendix page for git revisions
  # (esp. if you have other code that you wrote besides the thesis)
  # appendices:
  # - chapters/git-revisions.qmd

bibliography: extras/bibliography.bib
# for changing citation style or including all bibtex entries
biblio-style: ieee

# for hyperlinks in the footer and (optional) git-revisions appendix
gitRepoLink: https://github.com/Doran-Penner/reed-thesis
gitTreeLink: https://github.com/Doran-Penner/reed-thesis/tree

filters:
  - template/treesitter-highlighting.lua
  - quarto
  - template/remove-appendix-part.lua

# lof: true
# lot: true
abbrs:
  ADT: Abstract data type
  BST: Binary search tree
  CAP: Consistency, availability, partition-tolerance
  CDC: Content-defined chunking
  CRDT: Conflict-free replicated data type
  LWW: Last-write-wins

# a thesis presented to [thedivisionof] [division]
thedivisionof: The Established Interdisciplinary Committee for
division: Mathematics and Computer Science
# approved for the [approvedforthe] \n ([department])
approvedforthe: Committee
department: Mathematics and Computer Science
# (place for advisor(s) to put their signatures)
advisor: James Fix
altadvisor: Marcus Robinson

fontsize: 12pt

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    realdocumentclass: template/reedthesis
    template: template/template.tex
    template-partials:
      - template/doc-class.tex
      - template/biblio.tex
    cite-method: biblatex
