project:
  type: book
  pre-render: quarto render template/prelims
  post-render: ./template/prelims/cleanup.bash

book:
  title: "Prolly Trees for State-Based CRDTs"
  author: "Doran Penner"
  date: "May 2026"
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - chapters/background.qmd
    - chapters/construction.qmd
    - chapters/properties.qmd
    - chapters/improvements.qmd
  appendices:
    - chapters/git-revisions.qmd

bibliography: extras/bibliography.bib
# for changing citation style or including all bibtex entries
biblio-style: ieee

filters:
  - template/treesitter-highlighting.lua
  - quarto
  - template/remove-appendix-part.lua

# lof: true
# lot: true
# TODO do I want this? if so, remember to update after everything
abbrs:
  CRDT: Conflict-free replicated data type
  DAG: Directed acyclic graph
  CAP: Consistency, availability, partition-tolerance
  MST: Merkle search tree
  CDC: Content-defined chunking
  ADT: Abstract data type

division: Mathematics and Computer Science
thedivisionof: The Established Interdisciplinary Committee for
department: Mathematics and Computer Science
advisor: James Fix
altadvisor: Marcus Robinson

fontsize: 12pt

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    realdocumentclass: template/reedthesis
    template: template/template.tex
    template-partials:
      - template/doc-class.tex
      - template/biblio.tex
    cite-method: biblatex
