# Background

<!-- TODO: overall, try to have more of a narrative. It's very okay and good to say "we're doing crdts and we'll talk about them later" and then give reasons _why_ we wanna talk about x y or z. -->

## Distributed systems

<!-- TODO define "node" here or in Introduction. Do text search to make sure I don't use the word before I define it. -->

We will loosely define a _service_ as an overarching container of programs and protocols that does something when put together. A service could just be a single program on a single device, but usually spans multiple programs and computers. For example, the Internet Protocol (IP) is a service that allows computers to reach and communicate with each other even when they're not directly connected.

A simple service architecture has some _server_ program(s) that other _client_ programs make requests to. Video streaming is one such service --- a home computer makes requests to e.g. Netflix's servers for content to watch.
This is called the client-server model.

The client-server model runs into scaling issues with just one server: no computer of today, regardless of how much processing power it has or how much bandwidth its network has, could possibly handle all of the requests that are demanded upon some services (e.g. a single computer serving all Google search results). As such, the work of handling all these requests must be managed amongst multiple computers.
A _distributed system_ is a service where multiple devices work together to provide some program or service, instead of one machine doing it all. [@distsys-textbook p. 2]

An old example of a distributed system is Grapevine [@grapevine], an early email service. Xerox had local electronic mail servers in its offices, and the workstations were connected to some local server; the servers were also connected to each other via telephone lines. Given this setup, Grapevine was designed to facilitate email getting from one workstation to another regardless of their location.
There were components for email delivery, authenictation, and so on, and each had to deal with its own challenges due to the distributed nature of the system. For example if the dial-up connection between two offices is down, what should the email-fetcher do --- stall until the line is back, or try again in an hour? These are the sorts of problems that come up with unreliable networks.

A _peer-to-peer_ system is a special kind of distributed system.
For the First International Conference on Peer-to-Peer Computing, peer-to-peer is defined as when
"the participants share a part of their own hardware resources ... These shared resources are necessary to provide the Service ... [and] are accessible by other peers directly, without passing intermediary entities. The participants of such a network are thus ... providers and ... requestors" [@p2p].
They additionally define "pure" peer-to-peer with the additional constraint that any single node can be removed without impacting service, and the network is "hybrid" otherwise.
<!-- TODO I don't love this direct quotation but it works for now. And maybe I should just give the entire quote instead of this dotdotdotted version? Come back later. -->

This is a complex definition and already shows the nuances of peer-to-peer systems. Most of the time, peer-to-peer is defined in contrast to a client-server architecture --- instead of marking a computer as either a client that requests data or server that responds to requests, all machines are equal in some sense and can operate as both clients and servers. An example of this is BitTorrent [@sam-thesis], which is used for file sharing: a node both downloads data from other nodes and provides data for upload to other nodes. This provides resilience, reduced load, and increased speed when many devices would otherwise all have to request the data from the same server.

Note that the line between client-server and peer-to-peer gets messy. For example, Dynamo [@dynamo] is a service from Amazon to provide a key-value store. The entire system operates as a server for external clients: a device can connect to some machine in the Dynamo system and ask for the value corresponding to some key. However, amongst the Dynamo servers the protocol is peer-to-peer --- no Dynamo node is structurally prioritized over another.
And the story gets even more complex with topics such as federation, which is somewhere between a fully peer-to-peer system and a client-server system.

<!-- TODO story for why we care about p2p? Come back after Introduction is more fleshed out. -->

### Challenges with distributed and peer-to-peer systems

Distributed and peer-to-peer systems have many challenges that need to be worked around [@distsys-textbook, p. 30].
Since the network can fail in inconsistent ways, there are many problems that plague all distributed systems: messages can be delayed, dropped, corrupted, delivered out-of-order, and duplicated.
A network _partition_ is when there's no path of communication between two sections of devices. For example, a building's machines could all be hard-wired to connect to each other, but the building suddenly loses connection to the wider internet.
Since network partitions could happen anywhere and at any time, nodes can become instantaneously unreachable, including partway through communication.
Thus protocols that send data over the network always have to assume that their messages could fail to send, and react accordingly.

And there are additional difficulties associated with peer-to-peer networks.
In many settings a peer-to-peer system is _open_, meaning that nodes are free to join or leave at any point in time.
For example, a new user can set up a BitTorrent client and start downloading and uploading files with peers that were already in the system. Similarly, nodes are often free to leave at any time for any reason. This is already true in distributed systems due to the faulty network, but it's generally assumed that a node will return in an unbounded but finite amount of time; in peer-to-peer systems, there is no guarantee that a node will ever return.
With openness also comes lack of trust --- if any device can join the BitTorrent system, the system might need to account for weak devices and actively malicious actors.

Finally, there is no inherent source of truth in peer-to-peer networks. In the traditional clients-and-one-server model, the authoritative copy of data lies with the server. But in a peer to peer network where different nodes may have different versions of some data, there's no architectural difference between the two to decide which node is "right."

All of this means that communication between nodes is inherently prone to failure, meaning that it cannot be completely trusted; and there is always the possibility that a node doesn't have the most up-to-date information.

### CAP theorem

To explore that last point, say there's some data somehow managed in the distributed system; for example, a list of people who are authorized to access a supercomputer.
The list could be stored by a single machine, or all nodes could store part of the list, or all nodes might have their own copy --- it doesn't matter for the example. But any machine in the distributed system is allowed to make changes to this list.

Now, say that one machine gets an access request and needs to check if the user is authorized, but one of the other nodes has been offline for a while. A decision then has to be made. It's possible that the currently-offline peer has important changes to the access list, so it is reasonable to stall until all peers are available. On the downside, that would mean waiting an indefinite length of time and the user wants to connect right now. So it's also reasonable to go with the most recent information available to the authorizing machine and hope that the offline node doesn't have any relevant pending changes.

Neither of these approaches is incorrect, but each has its benefits and drawbacks. By proceeding without connection, there is the possibility of accessing out-of-date information; by waiting until all peers are available, we indefinitely delay responses. More formally, there are three properties that one might desire from data stored in a distributed system.

Consistency
: every query of the data returns the most up-to-date version or an error. (So we don't get stale data.)

Availability
: every query of the data returns something, regardless of if it's correct. (So we're not hanging forever waiting for a response.)

Partition tolerance
: the system still works with arbitrary partitions of the network. (So we don't crash when one node becomes unreachable.)

Unfortunately, we cannot have all three of these. This is known as the _CAP theorem_, conjectured in @brewer-conjecture and proven in @brewer-proof. It doesn't matter exactly how the data is stored: as long as any node in the system can make changes to it and can also go offline, you cannot guarantee both consistency and availability in the event of a network partition.

There are problems with the CAP theorem as a tool of analysis for a distributed system; see @kleppmann-cap for discussion of alternative frameworks.
For one, the proof relies on a specific definition of consistency --- atomic, linearizable transactions --- and only focuses on a single value to be written. The theorem also says that a system can get both consistency and availability when there is no partition-tolerance; while true, in the real world of distributed systems one always has to design around a network partition in case it occurs. (No distributed system should be designed while ignoring the possibility of a partition.)
Furthermore, the CAP theorem does not consider latency at all. If all nodes are reachable but it'll take 20 minutes to get updates, is it worth the wait? It depends on the application and the CAP theorem does not address this question.
But generally speaking, there is usually a tradeoff of availability in distributed systems. Applications that require good availability have to forgo some amount of consistency, whether that's due to latency or partition tolerance.
And the CAP impossibility means there is a large space of options that applications can choose from depending on their needs.

### Assumed infrastructure

<!-- TODO anything else? -->

With all of that, there are a ton of different settings and models that distributed systems must operate in. For our purposes, we will make the following assumptions about the system we're operating in:

1. We work in a peer-to-peer system. Nodes may permanently join or leave at any time, but we are not concerned with malicious nodes or consensus --- all machines in the network are assumed to be functional and well-intentioned.
2. The network loosely connects all active nodes. The network may fail, but eventually it will recover and the network graph will be fully connected.
3. Not all machines will have direct connections with one another, but there is some protocol (such as a gossip or anti-entropy algorithm [@gossip]) to disseminate information across all machines or to talk to any other machine directly by passing messages.

## Abstract data types

<!-- TODO make this writing better later. -->

Given all that, we want to create a reliable service in this peer-to-peer system. But what does this "service" constitute? Something like collaborative document editing requires service-specific logic, but the underlying tools can be generalized. A simple text document (without any formatting) can be seen as a long list of characters, so it is worth considering more abstract "services" which just provide a common data structure interface.
Generally, we can think about creating an _abstract data type_ (ADT) in our peer-to-peer system that is accessible and modifiable by any node.

What should a node be able to do? It depends on the interface to the ADT. For example, a queue [@clrs, p. 234] is a data structure that supports two operations: `Enqueue`, which puts a new value into the back of the line, and `Dequeue`, which removes & returns the first item in line. One could use a queue for anything that needs a first-come-first-serve structure (e.g. restaurant orders to fulfill), and it doesn't matter how it's implemented. Under the hood, there could be a linked list storing all the data, or a tree, or anything else --- it doesn't matter as long as the abstract interface is respected. We also can reason about the _abstract state_ of the ADT, which is the state that it represents. If we `Enqueue` the numbers 4, 7, and 2 in that order, then the abstract state is that the queue contains 4, 7, and 2 and the next thing to be `Dequeue`d will be 4. The underlying implementation still may store the data in any which way, but it's useful to discuss the abstract state.

<!-- TODO fix up the "story" once Introduction is written. But for now I'm just gonna state info. -->
There are a lot of ADTs that we might want to implemenmt in a peer-to-peer system. Something we'll dig more into later is an _ordered dictionary_. This consists of a set of _keys_ (collection without duplicates) that has some ordering, e.g. the keys are numbers and the ordering is "less-than." Each key is additionally attached to some _value_. Dictionaries are also called (key-value) maps since they map keys to values. An ordered dictionary allows the following operations:

<!-- TODO is there a better way of presenting this? -->
- `val = get(key)`, which (if `key` is in the dictionary) returns that key's value;
- `vals = get_range(small_key, big_key)` returns all values which have keys in the range `[small_key, big_key]`;
- `update(key, value)` (if `key` is in the dictionary) sets that key to have a new value;
- `insert(key, value)` which adds a new key-value pair to the dictionary;
- `delete(key)` which deletes a key-value pair from the dictionary.

<!-- TODO should I say you can use it as a list? -->
Ordered dictionaries are very versatile data structures.
TODO give some example uses.
A common way to implement them is with binary search trees, but we'll cover implementation in more detail later.

<!--
- A "set" ADT is an unordered collection of unique items. You can insert values and later check if some value is in the set.
- An "ordered set" is a set where the keys have some ordering. You can thus query a range of values at a time.
- A "map" ADT is a mapping from keys to values. You can insert (k,v) pairs and then later query by key to get that value (if it was previously stored in the map). Generally treated like a set ADT on the keys with some extra info (the values) attached to each key, and that extra info can be changed.
- A "dictionary" is another word for this map ADT.
- An "ordered dictionary" is a dictionary where the keys also have some (total?) ordering, allowing range queries.
-->

## CRDTs

One way to implement ADTs in a peer-to-peer system is with a _conflict-free replicated data type_, or CRDT [@shapiro-crdt]. That is

- an abstract _data type_, e.g. number, list, or dictionary;
- that is _replicated_, where there are multiple copies of the data on different machines;
- and _conflict-free_, meaning that there is some way of combining copies that always succeeds.

This gets excellent availability and partition tolerance by just having some local copy of the shared data. Additionally, having many copies means that there are inherent backups to prevent data loss.
This does sacrifice perfect consistency, since (before network communication) it's likely that a node's copy of the data will not have peers' changes.
Instead, CRDTs settle for _strong eventual consistency_: given enough communication between nodes (when the network is up), all nodes eventually agree upon the final version [@eventual-consistency]. In many applications, this is a reasonable tradeoff: git, for example, doesn't require internet connection while working but only to share and retrieve data from others.

Ensuring strong eventual consistency is the hard part of CRDTs. There must be some way to guarantee that any two replicas will converge to the same value with communication.
There are two common ways to ensure this: either by focusing on the state of the data or the operations applied to it.

### State-based

<!-- TODO should I have more narrative for these subsections? Methinks not -->

State-based CRDTs ensure strong eventual consistency via a join-semilattice [@lattice] over the states.

:::{#def-semilattice}
#### Join-semilattice
Let $S$ be a set and $\lor : S \times S \to S$ be a binary operation (our "join") on $S$. Then $S$ is a join-semilattice via $\lor$ if the operation has the following properties for all $x, y, z \in S$:

1. Associativity: $(x \lor y) \lor z = x \lor (y \lor z)$. It doesn't matter what order the join is applied in.
2. Commutativity: $x \lor y = y \lor x.$ There's no "sidedness" to the join.
3. Idempotency: $x \lor x = x$. Self-joining does nothing.
:::

<!-- TODO wording -->
This join operation is also called a least upper bound because it yields a smallest-possible way to combine two elements of a set. If these properties hold, then $\lor$ gives us a minimal way that we can always combine two items of a set.

This gives us a way to guarantee strong eventual consistency! Given any two copies of some data, we can join them via some defined operation. No matter the order that this propogates throughout the distributed system, if nodes (without making any new changes) keep joining pair-wise then eventually all will have the same state.
So if we can define an operation on our data that has these properties, then we have a state-based CRDT.

For a simple example, we can easily make a max-number value with state-based power. If the state space $S = \mathbb{R}$, then we can define the join as the maximum of its two inputs. We can verify that this satisfies all the properties: the maximum of any number with itself is itself, and the maximum function does not care about order of inputs or application.
We can also easily make a grow-only set, an unordered collection without duplicates which only allows adding more items.
Let $\lor = \cup$ (set union) over all sets. Set union is associative, idempotent, and commutative; this means that we get a join-semilattice, meaning this is another CRDT.
<!-- set of all sets :( -->

### Op-based

Operation-based CRDTs achieve strong eventual consistency by requiring that all operations done on the data are commutative: that is, you can apply a collection of operations $a, b, c, \dots$ in any order and the outcome will be the same.
When this is the case, we also get a CRDT.
Nodes share changes by sending out the operations they did as soon as they happened; when a node receives an operation, it simply applies that to its data.
Since we have commutativity, node $A$ doing operation $a$ and then receiving & applying operation $b$ gives the same output as node $B$ doing operation $b$ and then applying the recieved operation $a$.

A simple operation-based CRDT is a number counter with addition (for example a bank account that can be added to or subtracted from). Addition over $\mathbb{R}$ is commutative, so we can represent all operations as `add(r)` for some $r \in \mathbb{R}$ and send $r$ to peer nodes. We can also represent a grow-only set using operations: the `add(x)` operation, which adds an item to a set, commutes with all other set additions.

### More complex examples

We've shown two ways to create a grow-only set CRDT. How could we implement a set CRDT that also allows for item removal?
Only considering the two operations `add` and `remove` which operate on one item at a time, we immediately encounter a problem: these are not commutative.
To illustrate this, consider applying the operations `add(7)`, `add(7)`, and then `remove(7)` in that order.
Since sets have no duplicates, the second `add` does nothing, and then the `remove` removes the $7$, yielding no overall change after the three operations.
But if we do `add(7)`, `remove(7)`, and then `add(7)`, the `add` at the end means there is overall a $7$ added to the set.

How can we fix this? It turns out that there is no real way to make a perfect set CRDT due to the above issue. However, we can create CRDTs which do a decent job at approximating a true set ADT [@shapiro-crdt, pp. 21-27].

One solution is storing two grow-only sets (called a two-phase or 2P-set), one called the "main" set $M$ and one called the "tombstone" set $T$.
To put an item in the set, add it to $A$ (which is a standard grow-only set). To remove an item, add it to $T$. So the abstract state of the overall 2P-set is $A ~\backslash~ T$.
This is easy to implement, since it's just two grow-only sets and nodes can transmit both sets' data as usual. However, it doesn't allow for re-adding elements which have already been removed. This could be alleviated to the $n$th degree by having $n$ pairs of added/removed sets in a hierarchy, but that is simply not practical or very useful most of the time.

Another solution is to have an operation-based counter on each item. Under the hood an integer is stored for each item observed, and shows the user all items whose counter is greater than zero.
For operations, it'll translate `add(7)` into incrementing the counter on $7$ by one. Similarly, `remove(7)` will be translated to subtract the $7$s counter by one bring it to $0$.
This might mean that even on a local copy, `remove(7)` won't actually remove the item from the set. This can be fixed by making the high-level `remove(7)` operation translate to subtracting $x$ from $7$'s counter. And similarly, `add(7)` will have to add enough to make the counter positive in the case that it becomes negative. Even with those changes, this won't always give intuitive semantics --- but it is still _a_ way to implement a CRDT.

Yet another way of getting around the problem is to attach unique identifiers to all items when `add`ing. We mix this with a 2P-set.
This means `add(7)` internally adds $7_\alpha$ to the added set, where $\alpha$ is some unique identifier for that item; then `remove(7)` will put all observed $7_*$ items into the tombstone set.
With this system, the only underlying operations that don't commute are adding and removing the same item with the same identifier; if we ensure that an application only removes items that it has seen, then all the real-world scenarios commute.

Implementing CRDTs gets even more complicated with more complex interfaces. What about a tree CRDT, which cannot have a cycle? Extra logic needs to be added to maintain the tree structure when moving subtrees [@kleppmann-move-op].
What about dictionaries, which are more complex than sets because they also attach changeable data to the keys? We can attach each key to a last-writer-wins register (meaning every operation now has some timestamp) or simply have the register as another grow-only set; both have their benefits and problems.
For a lot of ADTs, there is no perfect way to represent them while still getting eventual consistency. However, we can come up with various ways to approximate them which have CRDT guarantees.

### Compare and contrast

<!-- Awkward balance & transition from "misc background" to "what we care about for this thesis." -->
<!-- TODO dewit -->

Both can emulate each other! Briefly explain why.

State-based can only grow. How do you subtract from a number?

Operation-based CRDTs need more infrastructure to function. If messages are dropped or duplicated, the system won't work; so there needs to be some kind of accounting for messages that were received.

State-based requires sending the entire state for every single join. And since that state will only grow, the cost of joining will increase over time. @delta-crdt created $\delta$-CRDTs to counteract this, but they start to get op-like infrastructure needs and are a fun state/op hybrid.

What about long network outages or a specific peer leaving for a long time? Operation-based might need to store its operation history, which makes it basically state-based.

What about new nodes joining? State is easy because you just send over any node's current state. Operation needs to send over its current state of the data as well as the "accounting" of what messages it last received from various nodes. It gets messy!

Generally op-based works better with strong active network because minimal data is sent back and forth. State-based works better with less-frequent merges.

<!-- TODO should I say this? It kinda gets said right in the next chapter. -->
We're gonna do state-based and try to fix some state-based problems.
