# Existing content-addressed CRDTs

More specific background, e.g. MST and MerDag.

## Merkle Search Tree

STUFF TO DISCUSS
- compare with delta-crdts
- what kinds of crdts can we make with this underlying structure? talk about the keys and the values and e.g. last-writer-wins reconciliation.
- discuss some range of other MST constructions: Inria, Dolt, XetHub, bup...

<!-- Anyways, explain the Merkle Search Tree paper. (Maybe use Dolt's version and prove those properties?) Do a ton of explaining and walk-through. Drive the main point: it's a key-value search tree that efficiently stores diffs. Talk about how this relates to state-based CRDTs, delta-CRDTs, and a nice way to represent it all if we use this content-addressing thing. -->

One of the biggest issues with state-based CRDTs is that the entire state needs to be shared in order to merge. This is fine with smaller states such as a number, but if the state is a list with thousands or millions of items it will quickly become prohibitive.

One approach to fix this is $\delta$-CRDTs. TODO should those go in the background? I don't need to cover them in detail, just explain them. In particular, why are we _not_ using them?

Another approach is taken by CITE PAPER for a tree-based key-value set, called a Merkle Search Tree (MST). They use a clever design to ensure that a given collection of keys and values has a unique representation; then trees can be compared by hashes of their roots and (subsequently) subtrees' roots to find the actual difference between the trees.

<!-- NOTE should I use the original paper's version or the Dolt version? Document it if it's the Dolt version -->

### Details of construction

<!-- should I put e.g. rolling hashes in the general background section? -->
TODO explain it

<!-- analysis & proofs -->
TODO analysis/proofs

<!-- recap/overview -->
Since a given collection of key-value pairs has a unique representation as an MST, we can easily compare two peers' trees by comparing their root hashes. If equal, the trees are equal and we do no more work. If not equal, we can compare every single child hash and only continue down the paths that differ. If the difference between the two trees is large, there will still be a large amount of work necessary to share the difference between the peers. But the work is asymptotically proportional to the difference of the trees, not the whole tree size.

### Benefits of the MST

<!-- TODO what do we gain from this? Recap the usefulness and go from there into "next steps" -->
That's pretty cool! What's the point? It gives us efficient state merge with large states.
<!-- It also means we get a cross-machine "pointer" which is pretty cool. -->
What else can we do with this idea? Some ideas...

- Make other data types like this (unique representation via hash)
  - We can also adapt the MST to other container structures. A "range tree" (used by the fast crdt guy) is a fine way to represent a list, where each key is the index and value is the character. (Or maybe we ignore the "keys" altogether and just store the data, indexing with metadata?) It's not the most efficient but it definitely works. And maybe we can optimize the storage nicely or something idk.
- Improve the chunking somehow. Not sure exactly how but surely there's a way.
- Further improve the update latency by optimistically sending over each modification as we get it (along with old & new hashes, path in tree, etc). Can fall back on original transfer protocol when needed.

## Merkle-DAG

There's also a ton here to talk about! Explain the Merkle-DAG and how it represents the Lamport time partial order. Then follow the paper as they use it to have timestamp payloads as well as each node itself having a CRDT.

Perhaps talk about the issues this paper mentions at the end? Or save that for later.

## The juicy questions

Look, we have these cool content-addressed structures! They let us do CRDT things and their structure can encode all the CRDT semantics/info we need (like tree of operations/states/etc). So.... _what else can we do with this?_

### Stick 'em together

Use the DAG and each payload is an MST. Heavy state-based has a cost of state duplication normally, but not if those states are already deduplicated like MSTs!

(Note: I need to formalize the merged nodes, shouldn't be hard but I gotta do it.)

### Other MST-like stuff

MSTs provide a structure-sharing key-value map. Can we do this kind of thing for other complex/container types? Think list, tree, dag, graph, string, etc. If we can just make a list we still get JSON! (MST for dict, new thing for list and maybe string, direct hash for int float bool etc.) That's a cool checkpoint.

### Blockchain stuff

A bunch of problems brought up at the end of the Merkle-CRDT paper are related to blockchain issues like having to keep the whole history. We could go down the blockchain path and talk about how to solve these issues.

### Storing "conflicts"

I have an idea for storing "application-level" conflicts with this structure sharing system, but I can't quite put it to words now.
Not sure if this actually requires special work or if we just talk about it as a special (and useful) case of e.g. `dag[str]` for line-level pijul conflicts.
Anyways that's another thing we could do.
