# Construction

One of the biggest issues with state-based CRDTs is that the entire state needs to be shared in order to join. This is fine with smaller states such as a register, but if the state is a list with thousands or millions of items it will quickly become prohibitive.
The problem is addressed by $\delta$-CRDTs, but those require more complex infrastructure and inherit some of the challenges of operation-based CRDTs.
Can we do better? A Prolly Tree is a data structure that provides a solution to this for ordered dictionary CRDTs, embedding information about what changed directly in its structure.
Here is how to construct one in stages.

## Hashing and content addressing

Checking if two values are equal means we need to check every bit of both values in the worst case. With lots of data in a a CRDT, this means that two nodes need to transmit their entire states --- this quickly gets expensive and we'd like to have another solution.
_Hashing_ assigns a mostly-unique tag to data.
This reduces the communication cost of equality checks, because we only have to compare the hash of the data to see if they're equal.

::: {#def-hash-func}
### Hash function
A _hash function_ is any function $H : \{0,1\}^* \to \{0,1\}^m$, mapping inputs of arbitrary length to some fixed length $m \in \mathbb{N}^+$.
:::

We can represent all data as a sequence of bits, though will practically consider larger units such as bytes.

A _collision_ in a hash function $H$ is a pair of inputs $x, y \in \{0,1\}^*$ such that $H(x) = H(y)$ but $x \neq y$.
A very simple hash function could e.g. map all inputs to the output of 0, but that's not very useful.
We are interested in functions with small chance of collision.

::: {#def-collision-resistance}
### Collision resistance
A hash function $H$ is _collision-resistant_ if it is infeasible for any probabilistic polynomial-time algorithm to find a collision in $H$ [@intro-modern-crypto-3rd, p. 168].^[This is an informal definition --- a proper one relies on _keyed_ hash functions (which are not relevant to our use) and a definition of probabilistic polynomial-time algorithms. See the textbook for the full treatment.]
:::

This implies that its output seems random and is hard to predict or backsolve: given the hash, there's no good way to figure out what input it came from besides just trying a bunch of inputs.

A note on terminology: the word "hash" is overloaded. You hash _(verb)_ some input with a hash function _(noun)_ and the output is the hash _(noun)_ of the input.

There necessarily are collisions in a hash function, even a collision-resistant one: since the output space is finite and the input space is infinite, an infinite class of inputs are pidgeonholed into the same output.
For our purposes, we'll ignore the chance of collisions. SHA-256, a ubiquitous cryptographic hash function, has $2^{256}$ theoretically-possible outputs and there are no known collisions even after decades of analysis.^[
There have been various attacks on reduced-strength versions of these hash functions: see @hashcrack1, @hashcrack2, and @hashcrack3 for the state of the art as of writing this.]
Even if there were some problem, we could use an additional hash function to supplement the original, swap out SHA-256 for an entirely new hash function with larger output space (like SHA3-512), or do many other things.
So from here on out, we'll assume that we have access to a collision-resistant hash function $H$ whose output is large enough that if $H(x) = H(y)$ then $x = y$ except with unimaginably small chance.

With that assumption, hashes let us cheaply check equality. If $H(x) = H(y)$, then $x$ almost always equals $y$. So if two nodes wish to compare some data (e.g. whether their state-based CRDT is in the same state), they can simply hash the entirety of their data and only share the hash. If the value is the same, then by our above assumption they have the same data and don't need to communicate further. If they don't have the same hash, then they'll need to share their full states as usual.
Thus in the optimistic case where two CRDT states are the same, the nodes only need to transfer a small amount of data.
<!-- TODO note that this relies on a consistent way to represent the data. -->

<!-- TODO remove this entire section? -->
_Content-addressed storage_ is a database that supports efficient queries via the hash of the desired content. So given a hash $h$, it will return the data $x$ for which $H(x) = h$ (if $x$ was previously put into the database).
Under the hood, it might be implemented as a dictionary with $(h, x)$ as the key-value pair; but for our purposes we will let other programs deal with the implementation details, and assume we have access to content-addressed storage that correctly retrieves data from its hash.

<!-- "hashes are also useful in distsys because they provide a concise way to reference data..." TODO -->
Content addressing is immensely useful in distributed systems because it provides a clear way to concisely reference data. Normal computer programs can do this with pointers, but those reference a location in memory that is specific to the program being run and the device that it's on. A hash is a deterministic function of the data which was hashed and is always the same, no matter what machine calculates the hash. This means it can be used as a stable, cross-machine reference to a block of data.
Using hashes to reference everything makes communication a lot quicker and easier while still remaining unambiguous.
<!-- Prolly trees have a lot of data that we want to reference by hash; content addressing means we generally only need to deal with hashes, and can easily get the content when desired. -->

## Merkle trees

Just taking a single hash of all the data is optimistic, since usually two states will be different (otherwise there's no point in joining). We can use hashing in a neat way spread out the comparison benefits to blocks of the data.

<!-- TODO Jim has opinions on how I should notate this stuff (with the word "extent" and range notation). -->
<!-- TODO jim thinks the subscripting notation here is messy and I kinda agree. Should I use range/extent, or sequence, or what? -->
<!-- TODO is this a place to use sequence notation? -->
<!-- TODO Marcus says to either give a true general definition or to give an informal definition outside of a #def environment -->
A _Merkle tree_ is a tree of hash pointers to other hash nodes, ending in leaves of actual data that is verified by the hashes [@merkle-tree].
To construct a Merkle tree, start with some data (e.g. a very long file). For each data block $x_i$ (e.g. each 1KiB section), compute its hash $h_i = H(x_i)$. Then construct a binary tree from the bottom up, recursively hashing pairs of hashes. For example, the parent of $h_1$ and $h_2$ (denoted $h_{1-2}$) stores $H(h_1||h_2)$, the hash of $h_1$ concatenated with $h_2$. And then its parent $h_{1-4} = H(h_{1-2}||h_{3-4})$, and so on. Eventually this leads to a single hash $h_{1-n} which is the parent of all $n$ leaf hashes, called the root hash.
Note that taking hashes of hashes in this way maintains collision resistance --- it is still computationally infeasible to find a collision in two Merkle tree root hashes.

<!-- TODO remove all the data representation stuff? -->
Merkle trees solve our problem of hashing large amounts of data. Assume that our state-based CRDT has some way to represent its current state in an ordered way, e.g. a binary string. Furthermore, assume that this representation is unique for a given state. Then we can construct a Merkle tree on e.g. 1-kibibyte chunks of its data. (This is a bit of extra storage, but not much --- we store about two hashes for every 1KiB, which is roughly 6% extra storage space.)
This Merkle tree can be used to dramatically reduce the amount of data that two nodes $A$ and $B$ must transfer when joining.
Each maintains a Merkle tree on their data, which for this example has four leaves. Notate $A$'s root hash as $a_{1-4}$ and $B$'s root hash as $b_{1-4}$.
Now $A$ and $B$ share their root hashes. If they are the same, then (with overwhelming probability) their data is the same and thus the states are the same.
And if the hashes are different, the states are different --- but we can find _where_ they differ. If $a_{1-4} \neq b_{1-4}$, then $A$ and $B$ can share the next layer's hashes: $a_{1-2}$, $a_{3-4}$, $b_{1-2}$, and $b_{3-4}$. (All of this data lives in content-addressable storage for easy retrieval.) If $a_{1-2} = b_{1-2}$, then that section of the Merkle tree is the same, so we don't need to go further down that path: the Merkle tree structure means that all the data in that subtree is identical. So $A$ and $B$ will only have to compare data in the right subtree where $a_{3-4} \neq b_{3-4}$. This process can recurse all the way down the tree until both nodes have a list of the leaf hashes that differ, which tells them what data they need to actually share. In the worst case, every hash differs between the two nodes and both need to share their entire states. But when only a small amount of data has changed, a Merkle tree means that two nodes may only need to share a small amount of data, which immensely reduces the communication cost of merging states.

<!-- TODO remove? -->
All of this relies on a standard way to represent and order the data. In some domains, such as tracking modifications to a large file, there is a natural way to do this. But some domains are harder. When implementing a set CRDT, how should its data be represented for the Merkle Tree? Sets don't have inherent order. There needs to be some representation that is unique to the state represented.
We'll eventually be implementing an ordered dictionary CRDT, so we'll use that ordering to create a consistent data representation.

## Rolling hash functions {#sec-rolling}

The scheme we just described works well sometimes, but it's not perfect. What if data is added to the start? For example, say our list CRDT serializes as a list of its values and some node adds data to the head of the list. This necessarily changes the hash of the first block in the Merkle tree, but furthermore has cascading effects --- all the data shift down the line a little bit, meaning that all chunks suddenly have new hashes. So our Merkle tree hash comparison would see that the nodes need to transmit all of their state, even though only a small amount of data actually differs.
This doesn't affect correctness, but can ruin our performance gains from using the Merkle tree comparison scheme. We want a way to have the Merkle tree improvements in most cases of data insertion, not just when new data is appended to the end.

Generally, _chunking_ is the process of breaking up a large sequence of data into smaller blocks, or chunks.
What we did initially with the Merkle tree is fixed-length chunking: draw a dividing line every $k$ bytes and those are the blocks. This is a decent deduplication system, but as shown above it doesn't take full advantage of data similarity. _Content-defined chunking_ (CDC) attempts to fix this boundary-shift problem by determining chunk boundaries (when to draw a line between blocks) based on the actual contents being chunked. It doesn't fix the duplication problem entirely, but good CDC is very efficient and dramatically reduces the problem when new data is inserted.

<!-- :::{#def-rolling-hash} -->
<!-- ###### Rolling hash -->
<!-- A _rolling hash_ is a hash function^[This is not a true collision-resistant hash function, but a "pretty random-looking" compromise so we can efficiently add new bytes.] that computes the hash of a sliding window of data. -->
<!-- Let x, y, z. Then -->
<!-- $$ -->
<!-- TODO. -->
<!-- $$ -->
<!-- ::: -->

A common way to do CDC is with a rolling hash. This is a hash function that is not collision-resistant, but its output is roughly uniformly distributed. The key feature of a rolling hash $R$ is that it computes a _sliding window_ of the data, meaning that the output of $R\Bigl((x_i)_{i=1}^n\Bigr)$ is the same as $R\Bigl((x_i)_{i=n-w+1}^n\Bigr)$ for some window width $w$.
The sliding window of the rolling hash means that small changes to the data will, with high probability, only affect one or two chunks.
If position of some changed data is more than $w$ behind the chunk's ending boundary at $x_e$, the decision to draw a boundary after $x_e$ cannot be affected since it's out of the window range. So it's possible that a new chunk boundary will be created in the middle of the existing chunk, or no boundaries will change.
Now if the changed data position is within $w$ of the ending chunk line, it's possible that it'll change the decision of whether to draw the existing chunk boundary. But by the previous argument about window width, it will not cascade to change the _following_ boundary unless the following block has size less than $w$. This is exceedingly unlikely, and the chance of this happening over and over again (cascading through the entirety of the data) is even more exceedingly unlikely.
Thus as long as the average block size is significantly larger than the window size (which we can configure to be true), we can confidently say that small changes to the data will only change one or two chunks except with negligible probability.

<!-- TODO I want an image :( -->

One common rolling hash is the Gear hash [@ddelta].
Notate our input data to be chunked as $(x_i)_{b=1}^n \in B^n$, where $B$ is the set of all bytes. Then $g_i$, the Gear hash up to byte $i$, has the following recursive definition:
\begin{align*}
g_0 &= 0; \\
g_i &= (g_{i-1} \ll 1) + \textsf{GearTable}[x_i] \mod 2^{32}.
\end{align*}
Given the Gear hash up to the previous byte, we shift those bits up by one (losing the top bit) and then add some constant from a lookup table called the \textsf{GearTable}. That table is simply a mapping from bytes to randomly-generated integers, constant across all uses of the Gear hash. Mod it all by $2^{32}$ since the Gear hash operates on 32-bit integers.^[This is indeed a sliding window with width 32. In expanded form, all values more than 32 values behind are multiplied by $2^{32}$, which makes them equal to $0 \mod 32$.]

To determine whether to draw a chunk boundary after byte $i$, the Gear hash has a "judgment function" that checks the top $k$ bits of $g_i$. If they're all $1$, then make a chunk boundary and restart the Gear hash after the boundary. Otherwise keep the previous state and keep going until a boundary is found or the end of the input is reached.
As long as the \textsf{GearTable} is randomly created and we're not too unlucky, the values of $g_i$ will be roughly uniform and the chance of the top $k$ bits all being one should be about $\frac1{2^k}$.
So to have chunks of average size $1$KiB, we'd set $k = \log_2(1024) = 10$.

There are further improvements to the Gear hash, such as in @fastcdc where the deduplication ratio and distrubution of chunk sizes is greatly improved, but we won't go into the details of modern constructions. All that is important for us is that we have access to some sliding-window chunking strategy that is efficient and usually won't cause a cascading effect of boundary changes when data is modified.
Then when nodes do the Merkle tree hash comparison there is less redundant data transfer.

## Search trees

We have now created a way to efficiently communicate the difference between two state-based CRDTs. If we have a standard way of representing and ordering the data of the state then we can do CDC on that data to determine where to draw chunk boundaries, construct a Merkle tree of that, and then do hash-based equality checks to figure out what chunks differ between two nodes. Prolly trees are a specialization of all this for search trees.

A binary search tree (BST) is a way to implement an ordered dictionary ADT, storing values that can be searched by key. Each node in the BST (starting from the root) has a key, its corresponding value, and two child nodes. The left subtree has keys less than the current node's key; similarly, the right subtree has keys greater than the current node's key.
To find a key $k$, start at the root and compare $k$ to the root's key. If they're the same, then we're done; if $k$ is greater, then go to the right child; otherwise $k$ is smaller so go to the left child. Repeat until we find the key or get to some node which doesn't have the correct-direction child, meaning that the key does not exist in this tree.

Generally, search tree nodes can have $n$ keys and $n+1$ children. If a node has two keys and the search key $k$ is not equal to either of them, then $k$ is less than both, greater than both, or between the two values; each of these options can have a child node pointer to continue the search down the tree. In practice, having larger blocks (e.g. a few hundred keys per block) improves performance because computers are better at loading a few large blocks of data instead of many small binary nodes.

Another nice property to have in a search tree is balancing. If the tree is balanced (meaning the children of a node are roughly even between its two subtrees), then operations on a search tree are very efficient --- we get $\O(\log(n))$ time to insert, update, and delete in the worst case since each level of the tree we go down will cut the space of nodes considered by a fraction ($\frac12$ for BSTs).

B-trees are a type of search tree that are heavily used in practice because they maintain balance and have large (parameterizable) block size [@btree].
Our modified Merkle tree is also balanced, since all the data is at the same level; and we can configure the CDC to create an average block size. Furthermore, we can use CDC to also determine chunk boundaries of the internal tree nodes, meaning that we get larger block sizes through the entire tree.
Thus our constructed Merkle-tree-with-CDC has the same desirable properties that make B-trees so common, meaning that it should work well if we can somehow use it as a search tree.

## Prolly Trees

Now we have all the tools we need to construct the final Prolly Tree:
a collision-resistant hash $H$,
content-addressed storage,
and a sliding-window content-defined chunker $C$.
When implementing an ordered dictionary with $n$ items, we can represent the state as an array of key-value pairs $A = ((k_i, v_i))_{i=1}^n$. Then:

1. Run our chunker $C$ on the input $A$, checking for boundaries after the end of each $a_i \in A$ (so we don't break apart the keys or values). This yields the chunks $(c_j)_{j=1}^m$.
3. For each chunk $c_j$:
   1. Get the hash of that chunk $h_j = H(c_j)$.
   2. Put $c_j$ in our content-addressable storage.
   3. Pair the largest key that is held in $c_j$ with $h_j$.
4. Concatenate all these new key-hash pairs into a new array $A' = ((k_j, h_j))_{j=1}^{m}$. Recurse on $A'$ until there is only one key-hash pair remaining. This is the root of the Prolly Tree.

And that's it!
We have created a Prolly Tree storing an ordered dictionary and all of its blocks can be accessed by our content-addressable storage.

Similar to a B-tree, we can search for data efficiently.
To find a key $k$ in the tree, first fetch the root block and compare $k$ to its keys. The smallest $k_x$ such that $k_x \ge k$ will store the subtree where $k$ might be stored; so fetch the block pointed to by $h_x$ (the "value" paired with $k_x$) to get another node for comparison.
Doing this process down the tree until the leaves will find $k$'s position in the tree and its data if it exists; and the search tree structure means that we get efficient (logathmic) access time.

We also use the Merkle tree with content-defined chunking for good efficiency in state-based comparison.
To compare states between two nodes, first they exchange root hashes. If they're the same, then the nodes have the same data; otherwise both fetch and exchange the data which their root hash references in the content-addressed storage. Any hashes in that block which are the same are known to be shared by both nodes, so they don't need to continue down those subtrees. Repeat the data block exchanges until both nodes have all blocks that differ from their own tree.
<!-- TODO anything else to say? -->

## Comparison of similar structures

The Prolly Tree that we've covered was created by @noms. But there have been many inventions of very similar data structures in the past 20 years; see @prolly-reinvent1 and @prolly-reinvent2 for all the details.
If you already have an ordering on the data and don't need searchability, you can just do a merkle tree with content-defined chunking (what we had before the search tree section). This is what @content-defined-merkle-tree does for very large files with lots of data similarity.
There's also the Merkle Search Tree [@mst], which is constructed a bit differently --- the hash of each key determines its height in the tree, and the key ordering determines which blocks point to what. It gets to the same end result of a history-independent search tree.
And there are many other inventions which aren't recorded.
We choose to use the Prolly Tree because it seems like a natural progression from many other tools like Merkle trees, but all choices are valid.
<!-- fewer edge cases (e.g. big gap), we want searchability, keys are also hashed and based in, anything else? At some point you just gotta pick something. -->
<!-- I find that the prolly tree approach is a bit more intuitive and has the hash structure built in which I like. But really you can do anything! DoltHub uses prolly trees. BlueSky uses MST. It's whatever. We're using prolly tree. -->
