# Improvements

Here are various ideas for improving and proving more about the Prolly Tree.
This is less formal and more of a collection for possible future tasks in this area.

## More rigorous runtime analysis

There was a lot of hand-waving with the runtime analysis of e.g. inserting a new key-value pair. This is because the chunking is messy and pseudorandom, but there is room to improve. It would be nice to have a formal statement of e.g. the probability that a single key-value change modifies 1, 2, or 3 chunks.

<!-- ## Improving the CDC -->

<!-- Dolt already did this, but I can talk a bit about how to make the chunking better. -->
<!-- This relates a lot to the formal runtime analysis --- maybe a true sliding-window system would yield better analysis and/or performance. -->

## Real-world performance studies

Generally, how useful is this structure in practice? Are there changes to the construction that make it faster to use? There are many projects using Polly Trees or some variant thereof, so it can't be that bad --- but it would be interesting to see the actual speed difference between a B-tree and Prolly Tree for lots of random operations.

## Range trees and other data types

We've only covered using the Prolly Tree for an actual ordered dictionary, but such a structure can implement other ADTs. For example, a "range tree" is a list implemented by a search tree, where the keys are indices and a value is the item at that index. This is slower than a standard array for reads, but for random writes the Prolly Tree takes logarithmic time instead of an array's linear cost. The Diamond Types library [@diamond-types] is extraordinarily fast compared to existing CRDT libraries and implements a list CRDT using a range tree; this is not a Prolly Tree that needs to deal with chunking and hashing, but nonetheless suggests that this is a potentially-fruitful way to represent lists.

Adding on to that, are there other ADTs that could be implemented as CRDTs with a Prolly Tree or something similar? If we allow putting range-tree lists as values of the Prolly Tree keys and vice versa, we can make a CRDT for JSON. It's unknown if this would be used in practice, but JSON is ubiquitous so perhaps this is a useful thing to create.

## Operation-like data transfer

The state-based Prolly Tree comparison is far more efficient in terms of data transfer, but still requires a logarithmic number of round trips between nodes to compare their states. If there are infrequent changes to the state, a node could instead just send what changed to peers and assume that they had the same state previously. Something like...

1. Node $A$ adds a key-value pair $(k, v)$, which results in the root hash changing from $old$ to $new$.
2. $A$ sends out the data $(old, k, v)$ to its peers.
3. A peer $B$ that receives this message compares its root hash to $old$. If they're the same, then $B$ simply adds $(k, v)$ to its Prolly Tree and recalculates the hashes as usual; since the starting hash was the same, $A$ and $B$ will have the same root hash $new$ afterward.
4. If the hashes were not equal, $B$ signals to $A$ that they have diverged and the two nodes do the full state-based tree comparison like normal.

This is an optimistic scenario, but always falls back on standard state-based join if the hash comparison fails so it won't yield invalid joins. This is essentially making the CRDT a hybrid between operation-based and state-based CRDTs, and the operation-based method may work well when the modification frequency is below some threshold.

## Dynamo-like sharding

The CRDT setting imagines that all nodes have their own full copy of the data, and the “distributed” part is about how to reconcile different versions. But each node can do whatever it needs to do all on its own.
On the other hand, the Dynamo [@dynamo] world imagines that all the nodes are working together in some way, parts of a whole. Each node might store only a few chunks of the whole search tree (called "sharding") and queries are always to the whole network.
They're very different models, exchanging replication (and availability) for consistency amongst the group.
But they cover similar topics, and perhaps there would be benefit in sharing ideas from each. Does the content-defined chunking of the Prolly Tree have any benefit in the sharded setting?
It's worth looking into.
